theme: jekyll-theme-minimal

title: Daniele Rama
description: ""

logo: /assets/images/logo.png

urls:
  twitter: https://twitter.com/daniele_rama
  linkedin: https://www.linkedin.com/in/danielerama
  github: https://github.com/danielerama
  scholar: https://scholar.google.com/citations?user=rnhYTUUAAAAJ&hl=en

github:
  is_project_page: false
  is_user_page: false
